name: Build and Publish Universal Wheel

on:
  release:
    types: [published]   # Automatically when you publish a GitHub Release
  workflow_dispatch:      # Allow manual triggering too

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tool
        run: pip install build

      - name: Build wheel and source distribution
        run: python -m build --sdist --wheel --outdir dist

      - name: Check the built files
        run: ls -lh dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist